server:
  port: 8092

# loggin
logging:
  file:
    path: ./resource-server/logs
  level:
    root: DEBUG
    com.binchencoder.oauth2: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
