server:
  port: 9000

logging:
  level:
    root: INFO
    com.binchencoder.spring: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: INFO

spring:
  thymeleaf:
    cache: false
  mvc:
    log-request-details: true


logout:
  notifies:
    urls:

login:
  success:
    default:
      target: http://localhost:8080/
