server:
  port: 9000

# logging
logging:
  file:
    path: ./sso-server/logs
  level:
    root: INFO
    com.binchencoder.oauth2: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.boot.autoconfigure: INFO

spring:
  application:
    name: oauth2-sso
  thymeleaf:
    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          messaging-client-auth-code:
#            provider: spring
#            client-id: messaging-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/authorized"
#            scope: message.read,message.write
#        provider:
#          spring:
#            authorization-uri: http://auth-server:9000/oauth2/authorize
#            token-uri: http://auth-server:9000/oauth2/token
#            jwk-set-uri: http://auth-server:9000/oauth2/jwks
  mvc:
    static-path-pattern: /**
    log-request-details: true
    view:
      prefix: classpath:/templates/
      suffix: .html

logout:
  notifies:
    urls: http://127.0.0.1:8080/logout

login:
  success:
    default:
      target: http://127.0.0.1:8080/
